version: '2.13'
services:
  frontend:
    build:
      context: .
      args:
        - NODE_ENV=local
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/code
    command: python manage.py runserver 0.0.0.0:8000
  