# Generated by Django 4.1.2 on 2022-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('svl', models.IntegerField()),
                ('tail', models.IntegerField()),
                ('tibia', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trapType', models.CharField(max_length=30, null=True)),
                ('latitute', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timeSet', models.DateTimeField(null=True)),
                ('timeChecked', models.DateTimeField()),
            ],
        ),
    ]
