# Generated by Django 4.1.2 on 2022-12-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='herp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.herp'),
        ),
    ]
